baseURL = 'https://azulika.github.io'
languageCode = 'en-us'
title = 'azulicat'
theme = "github-style"

HasCJKLanguage = true


[params]
  avatar =  "/images/cocktail-export.gif"
  author = "azulicat"
  nickName = "indigo372"
  description = "Nec audiendi qui solent dicere, Vox populi, vox Dei, quum tumultuositas vulgi semper insaniae proxima sit."
  #github = "MeiK2333"
  #facebook = "MeiK2333"
  #twitter = "MeiK2333"
  #linkedin = "MeiK2333"
  #instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  #email = "meik2333@gmail.com"
  #url = "https://meik2333.com"
  #keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/favicon.ico"
  location = "Japan"
  #userStatusEmoji = "😀"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  archive = "archives"

# 空白直改行
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

# 関連
[related]
  includeNewer = true
  threshold = 90
  toLower = true

[[related.indices]]
  name = "keywords"
  weight = 10

[[related.indices]]
  name = "tags"
  weight = 60

[[related.indices]]
  name = "logos"
  weight = 80

[[related.indices]]
  name = "date"
  weight = 10